name: PreScaleOperator
on:
  push:
    branches:
      - master
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Go Modules
        run: |
          go mod download
      #Install and configure a kind cluster
#      - uses: engineerd/setup-kind@v0.5.0
#        with:
#          version: "v0.10.0"
      - name: Setup Operator SDK
        run: |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.4.2/operator-sdk_linux_amd64
          chmod +x operator-sdk_linux_amd64 && sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
      - name: Setup KubeBuilder
        run: |
          os=$(go env GOOS)
          arch=$(go env GOARCH)

          # download kubebuilder and extract it to tmp
          curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/

          # move to a long-term location and put it on your path
          # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
          sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin
#      - name: Testing
#        run: |
#          kubectl cluster-info
#          kubectl get pods -n kube-system
#          echo "current-context:" $(kubectl config current-context)
#          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Run tests
        run: |
          make test