name: PreScaleOperator
on:
  push:
    branches:
      - master
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Setting up GOPATH
        run: |
          env | grep GOPATH
      - name: Run tests
        run: |
          make test